export const user = [{
    fullname: 'Hoàng Vũ',
    password: '12345',
    username: 'lehoangvuvt',
    address: '89/6 Huyen tran cong chua',
    phone: '0949661867',
    role: 'admin',
    birthday: "18/03/1996",
},
{
    fullname: 'Hoàng Minh',
    password: '12345',
    username: 'minhvt',
    address: '89/6 Huyen tran cong chua',
    phone: '0949661867',
    role: 'admin',
    birthday: "18/03/1996",
},
{
    fullname: 'Hoàng Minh',
    password: '12345',
    username: 'minhvt1',
    address: '89/6 Huyen tran cong chua',
    phone: '0949661867',
    role: 'admin',
    birthday: "18/03/1996",
},
{
    fullname: 'Hoàng Minh',
    password: '12345',
    username: 'minhvt2',
    address: '89/6 Huyen tran cong chua',
    phone: '0949661867',
    role: 'admin',
    birthday: "18/03/1996",
},
{
    fullname: 'Hoàng Minh',
    password: '12345',
    username: 'minhvt3',
    address: '89/6 Huyen tran cong chua',
    phone: '0949661867',
    role: 'customer',
    birthday: "18/03/1996",
},
{
    fullname: 'Hoàng Minh',
    password: '12345',
    username: 'minhvt4',
    address: '89/6 Huyen tran cong chua',
    phone: '0949661867',
    role: 'admin',
    birthday: "18/03/1996",
},
{
    fullname: 'Hoàng Minh',
    password: '12345',
    username: 'minhvt5',
    address: '89/6 Huyen tran cong chua',
    phone: '0949661867',
    role: 'customer',
    birthday: "18/03/1996",
},
{
    fullname: 'Hoàng Minh',
    password: '12345',
    username: 'minhvt6',
    address: '89/6 Huyen tran cong chua',
    phone: '0949661867',
    role: 'customer',
    birthday: "18/03/1996",
}
]

export const phones = [{
    phoneID: "p1",
    imgLink: "https://didongthongminh.vn/upload_images/2018/10/iphone7-plus-gold-1-300x400.png",
    phoneName: "Iphone 7s",
    manufacturer: "Apple",
    country: "USA",
    price: "12000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p5",
    imgLink: "https://didongthongminh.vn/upload_images/2018/10/iphone7-plus-gold-1-300x400.png",
    phoneName: "Iphone 7s",
    manufacturer: "Apple",
    country: "USA",
    price: "12000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p6",
    imgLink: "https://didongthongminh.vn/upload_images/2018/10/iphone7-plus-gold-1-300x400.png",
    phoneName: "Iphone 7s",
    manufacturer: "Apple",
    country: "USA",
    price: "12000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
}
    ,
{
    phoneID: "p7",
    imgLink: "https://didongthongminh.vn/upload_images/2018/10/iphone7-plus-gold-1-300x400.png",
    phoneName: "Iphone 7s",
    manufacturer: "Apple",
    country: "USA",
    price: "12000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p8",
    imgLink: "https://didongthongminh.vn/upload_images/2018/10/iphone7-plus-gold-1-300x400.png",
    phoneName: "Iphone 7s",
    manufacturer: "Apple",
    country: "USA",
    price: "12000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p9",
    imgLink: "https://didongthongminh.vn/upload_images/2018/10/iphone7-plus-gold-1-300x400.png",
    phoneName: "Iphone 7s",
    manufacturer: "Apple",
    country: "USA",
    price: "12000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
}
    ,
{
    phoneID: "p2",
    imgLink: "https://didongthongminh.vn/upload_images/2018/11/Samsung-Galaxy-S9-plus-%C4%91en.png",
    phoneName: "Samsung Galaxy S9",
    manufacturer: "Samsung",
    country: "Korea",
    price: "15000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p10",
    imgLink: "https://didongthongminh.vn/upload_images/2018/11/Samsung-Galaxy-S9-plus-%C4%91en.png",
    phoneName: "Samsung Galaxy S9",
    manufacturer: "Samsung",
    country: "Korea",
    price: "15000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p11",
    imgLink: "https://didongthongminh.vn/upload_images/2018/11/Samsung-Galaxy-S9-plus-%C4%91en.png",
    phoneName: "Samsung Galaxy S9",
    manufacturer: "Samsung",
    country: "Korea",
    price: "15000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p12",
    imgLink: "https://didongthongminh.vn/upload_images/2018/11/Samsung-Galaxy-S9-plus-%C4%91en.png",
    phoneName: "Samsung Galaxy S9",
    manufacturer: "Samsung",
    country: "Korea",
    price: "15000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p13",
    imgLink: "https://didongthongminh.vn/upload_images/2018/11/Samsung-Galaxy-S9-plus-%C4%91en.png",
    phoneName: "Samsung Galaxy S9",
    manufacturer: "Samsung",
    country: "Korea",
    price: "15000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p14",
    imgLink: "https://didongthongminh.vn/upload_images/2018/11/Samsung-Galaxy-S9-plus-%C4%91en.png",
    phoneName: "Samsung Galaxy S9",
    manufacturer: "Samsung",
    country: "Korea",
    price: "15000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p15",
    imgLink: "https://didongthongminh.vn/upload_images/2018/11/Samsung-Galaxy-S9-plus-%C4%91en.png",
    phoneName: "Samsung Galaxy S9",
    manufacturer: "Samsung",
    country: "Korea",
    price: "15000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p3",
    imgLink: "https://msmobile.com.vn/images/products/2019/11/04/large/google-pixel-3-msmobile-1_1572845900.jpg",
    phoneName: "Google Pixel XL",
    manufacturer: "Google",
    country: "USA",
    price: "9000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p16",
    imgLink: "https://msmobile.com.vn/images/products/2019/11/04/large/google-pixel-3-msmobile-1_1572845900.jpg",
    phoneName: "Google Pixel XL",
    manufacturer: "Google",
    country: "USA",
    price: "9000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p17",
    imgLink: "https://msmobile.com.vn/images/products/2019/11/04/large/google-pixel-3-msmobile-1_1572845900.jpg",
    phoneName: "Google Pixel XL",
    manufacturer: "Google",
    country: "USA",
    price: "9000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p18",
    imgLink: "https://msmobile.com.vn/images/products/2019/11/04/large/google-pixel-3-msmobile-1_1572845900.jpg",
    phoneName: "Google Pixel XL",
    manufacturer: "Google",
    country: "USA",
    price: "9000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p19",
    imgLink: "https://msmobile.com.vn/images/products/2019/11/04/large/google-pixel-3-msmobile-1_1572845900.jpg",
    phoneName: "Google Pixel XL",
    manufacturer: "Google",
    country: "USA",
    price: "9000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p20",
    imgLink: "https://msmobile.com.vn/images/products/2019/11/04/large/google-pixel-3-msmobile-1_1572845900.jpg",
    phoneName: "Google Pixel XL",
    manufacturer: "Google",
    country: "USA",
    price: "9000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p4",
    imgLink: "https://cdn.didongthongminh.vn/upload_images/2019/09/xiaomi-redmi-8-600x600.jpg",
    phoneName: "Xiaomi Redmi 8",
    manufacturer: "Xiaomi",
    country: "China",
    price: "9000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p21",
    imgLink: "https://cdn.didongthongminh.vn/upload_images/2019/09/xiaomi-redmi-8-600x600.jpg",
    phoneName: "Xiaomi Redmi 8",
    manufacturer: "Xiaomi",
    country: "China",
    price: "9000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p22",
    imgLink: "https://cdn.didongthongminh.vn/upload_images/2019/09/xiaomi-redmi-8-600x600.jpg",
    phoneName: "Xiaomi Redmi 8",
    manufacturer: "Xiaomi",
    country: "China",
    price: "9000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p23",
    imgLink: "https://cdn.didongthongminh.vn/upload_images/2019/09/xiaomi-redmi-8-600x600.jpg",
    phoneName: "Xiaomi Redmi 8",
    manufacturer: "Xiaomi",
    country: "China",
    price: "9000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p24",
    imgLink: "https://cdn.didongthongminh.vn/upload_images/2019/09/xiaomi-redmi-8-600x600.jpg",
    phoneName: "Xiaomi Redmi 8",
    manufacturer: "Xiaomi",
    country: "China",
    price: "9000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p25",
    imgLink: "https://cdn.didongthongminh.vn/upload_images/2019/09/xiaomi-redmi-8-600x600.jpg",
    phoneName: "Xiaomi Redmi 8",
    manufacturer: "Xiaomi",
    country: "China",
    price: "9000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p26",
    imgLink: "https://cdn.didongthongminh.vn/upload_images/2019/09/xiaomi-redmi-8-600x600.jpg",
    phoneName: "Xiaomi Redmi 8",
    manufacturer: "Xiaomi",
    country: "China",
    price: "9000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
{
    phoneID: "p27",
    imgLink: "https://cdn.didongthongminh.vn/upload_images/2019/09/xiaomi-redmi-8-600x600.jpg",
    phoneName: "Xiaomi Redmi 8",
    manufacturer: "Xiaomi",
    country: "China",
    price: "9000000",
    quantity: 20,
    description: "This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe This is iphone 7s. Not only you can buy it. Maybe ",
},
]

export const orders = [
    { orderId: 'OID000001', orderOwner: 'minhvt', address: '89/6 HTCC', phone: '0949661867', orderStatus: 1, date: '12/03/2020' },
    { orderId: 'OID000002', orderOwner: 'minhvt', address: '89/6 HTCC', phone: '0949661867', orderStatus: 1, date: '13/03/2020' },
    { orderId: 'OID000003', orderOwner: 'minhvt', address: '89/6 HTCC', phone: '0949661867', orderStatus: 1, date: '14/03/2020' },
    { orderId: 'OID000004', orderOwner: 'minhvt', address: '89/6 HTCC', phone: '0949661867', orderStatus: 1, date: '15/03/2020' },
    { orderId: 'OID000005', orderOwner: 'minhvt', address: '89/6 HTCC', phone: '0949661867', orderStatus: 1, date: '16/03/2020' },
    { orderId: 'OID000006', orderOwner: 'minhvt', address: '89/6 HTCC', phone: '0949661867', orderStatus: 1, date: '16/03/2020' },
    { orderId: 'OID000007', orderOwner: 'minhvt', address: '89/6 HTCC', phone: '0949661867', orderStatus: 1, date: '16/03/2020' },
    { orderId: 'OID000008', orderOwner: 'minhvt', address: '89/6 HTCC', phone: '0949661867', orderStatus: 1, date: '16/03/2020' },
]

export const orderItems = [
    { orderId: 'OID000001', phoneName: 'Iphone 7s', unitPrice: 1200999, quantity: 1, },
    { orderId: 'OID000001', phoneName: 'Iphone 8s', unitPrice: 1200999, quantity: 3 },
    { orderId: 'OID000001', phoneName: 'Samsung Galaxy S9', unitPrice: 1200999, quantity: 7 },
    { orderId: 'OID000001', phoneName: 'Xiaomi', unitPrice: 1200999, quantity: 5 },
    { orderId: 'OID000002', phoneName: 'Iphone 7s', unitPrice: 1200999, quantity: 1, },
    { orderId: 'OID000002', phoneName: 'Iphone 8s', unitPrice: 1200999, quantity: 3 },
    { orderId: 'OID000002', phoneName: 'Samsung Galaxy S9', unitPrice: 1200999, quantity: 7 },
    { orderId: 'OID000002', phoneName: 'Xiaomi', unitPrice: 1200999, quantity: 5 },
    { orderId: 'OID000003', phoneName: 'Iphone 7s', unitPrice: 1200999, quantity: 1, },
    { orderId: 'OID000003', phoneName: 'Iphone 8s', unitPrice: 1200999, quantity: 3 },
    { orderId: 'OID000003', phoneName: 'Samsung Galaxy S9', unitPrice: 1200999, quantity: 7 },
    { orderId: 'OID000003', phoneName: 'Xiaomi', unitPrice: 1200999, quantity: 5 },
    { orderId: 'OID000004', phoneName: 'Iphone 7s', unitPrice: 1200999, quantity: 1, },
    { orderId: 'OID000004', phoneName: 'Iphone 8s', unitPrice: 1200999, quantity: 3 },
    { orderId: 'OID000004', phoneName: 'Samsung Galaxy S9', unitPrice: 1200999, quantity: 7 },
    { orderId: 'OID000004', phoneName: 'Xiaomi', unitPrice: 1200999, quantity: 5 },
    { orderId: 'OID000005', phoneName: 'Iphone 7s', unitPrice: 1200999, quantity: 1, },
    { orderId: 'OID000005', phoneName: 'Iphone 8s', unitPrice: 1200999, quantity: 3 },
    { orderId: 'OID000005', phoneName: 'Samsung Galaxy S9', unitPrice: 1200999, quantity: 7 },
    { orderId: 'OID000005', phoneName: 'Xiaomi', unitPrice: 1200999, quantity: 5 },
    { orderId: 'OID000006', phoneName: 'Iphone 7s', unitPrice: 1200999, quantity: 1, },
    { orderId: 'OID000006', phoneName: 'Iphone 8s', unitPrice: 1200999, quantity: 3 },
    { orderId: 'OID000006', phoneName: 'Samsung Galaxy S9', unitPrice: 1200999, quantity: 7 },
    { orderId: 'OID000006', phoneName: 'Xiaomi', unitPrice: 1200999, quantity: 5 },
    { orderId: 'OID000007', phoneName: 'Iphone 7s', unitPrice: 1200999, quantity: 1, },
    { orderId: 'OID000007', phoneName: 'Iphone 8s', unitPrice: 1200999, quantity: 3 },
    { orderId: 'OID000007', phoneName: 'Samsung Galaxy S9', unitPrice: 1200999, quantity: 7 },
    { orderId: 'OID000007', phoneName: 'Xiaomi', unitPrice: 1200999, quantity: 5 },
    { orderId: 'OID000008', phoneName: 'Iphone 7s', unitPrice: 1200999, quantity: 1, },
    { orderId: 'OID000008', phoneName: 'Iphone 8s', unitPrice: 1200999, quantity: 3 },
    { orderId: 'OID000008', phoneName: 'Samsung Galaxy S9', unitPrice: 1200999, quantity: 7 },
    { orderId: 'OID000008', phoneName: 'Xiaomi', unitPrice: 1200999, quantity: 5 },
];
export const ratings = [
    { phoneID: 'p1', rating: 3, username: 'minhvt', date: '20/03/2020' },
    { phoneID: 'p1', rating: 1, username: 'minhvt2', date: '20/03/2020' },
    { phoneID: 'p1', rating: 2, username: 'minhvt3', date: '20/03/2020' },
    { phoneID: 'p1', rating: 4, username: 'minhvt4', date: '20/03/2020' },
    { phoneID: 'p2', rating: 1, username: 'minhvt', date: '20/03/2020' },
    { phoneID: 'p2', rating: 2, username: 'minhvt2', date: '20/03/2020' },
    { phoneID: 'p2', rating: 1, username: 'minhvt3', date: '20/03/2020' },
    { phoneID: 'p2', rating: 5, username: 'minhvt4', date: '20/03/2020' },
    { phoneID: 'p2', rating: 2, username: 'minhvt5', date: '20/03/2020' },
    
];